# SPDX-FileCopyrightText: 2023 SPDX contributors
#
# SPDX-License-Identifier: MIT

name: Lint and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node modules and build plugin
        run: |
            npm ci
            npm run build

      - name: Install node modules and build example
        run: |
          cd examples
          npm ci
          npm run build

      - name: Check linter
        run: npm run lint-check
